interface price {
	tile_id: number
	achat_nu: number
	achat_bar?: number
	acheter_restau?: number
	achat_disco?: number
	loyer_nu: number
	loyer_bar?: number
	loyer_restau?: number
	loyer_disco?: number
}

export const Price: price[] = [
	{
		tile_id: 1,
		achat_nu: 1,
		achat_bar: 2,
		acheter_restau: 3,
		achat_disco: 4,
		loyer_nu: 1,
		loyer_bar: 2,
		loyer_restau: 3,
		loyer_disco: 4,
	},
	{
		tile_id: 2,
		achat_nu: 1,
		achat_bar: 2,
		acheter_restau: 3,
		achat_disco: 4,
		loyer_nu: 1,
		loyer_bar: 2,
		loyer_restau: 3,
		loyer_disco: 4,
	},
	{
		tile_id: 5,
		achat_nu: 1,
		achat_bar: 2,
		acheter_restau: 3,
		achat_disco: 4,
		loyer_nu: 1,
		loyer_bar: 2,
		loyer_restau: 3,
		loyer_disco: 4,
	},
	{
		tile_id: 7,
		achat_nu: 1,
		achat_bar: 2,
		acheter_restau: 3,
		achat_disco: 4,
		loyer_nu: 1,
		loyer_bar: 2,
		loyer_restau: 3,
		loyer_disco: 4,
	},
	{
		tile_id: 9,
		achat_nu: 1,
		achat_bar: 2,
		acheter_restau: 3,
		achat_disco: 4,
		loyer_nu: 1,
		loyer_bar: 2,
		loyer_restau: 3,
		loyer_disco: 4,
	},
	{
		tile_id: 11,
		achat_nu: 1,
		achat_bar: 2,
		acheter_restau: 3,
		achat_disco: 4,
		loyer_nu: 1,
		loyer_bar: 2,
		loyer_restau: 3,
		loyer_disco: 4,
	},
	{
		tile_id: 13,
		achat_nu: 1,
		achat_bar: 2,
		acheter_restau: 3,
		achat_disco: 4,
		loyer_nu: 1,
		loyer_bar: 2,
		loyer_restau: 3,
		loyer_disco: 4,
	},
	{
		tile_id: 16,
		achat_nu: 1,
		achat_bar: 2,
		acheter_restau: 3,
		achat_disco: 4,
		loyer_nu: 1,
		loyer_bar: 2,
		loyer_restau: 3,
		loyer_disco: 4,
	},
	{
		tile_id: 17,
		achat_nu: 1,
		achat_bar: 2,
		acheter_restau: 3,
		achat_disco: 4,
		loyer_nu: 1,
		loyer_bar: 2,
		loyer_restau: 3,
		loyer_disco: 4,
	},
	{
		tile_id: 19,
		achat_nu: 1,
		achat_bar: 2,
		acheter_restau: 3,
		achat_disco: 4,
		loyer_nu: 1,
		loyer_bar: 2,
		loyer_restau: 3,
		loyer_disco: 4,
	},
	{
		tile_id: 21,
		achat_nu: 1,
		achat_bar: 2,
		acheter_restau: 3,
		achat_disco: 4,
		loyer_nu: 1,
		loyer_bar: 2,
		loyer_restau: 3,
		loyer_disco: 4,
	},
	{
		tile_id: 23,
		achat_nu: 1,
		achat_bar: 2,
		acheter_restau: 3,
		achat_disco: 4,
		loyer_nu: 1,
		loyer_bar: 2,
		loyer_restau: 3,
		loyer_disco: 4,
	},
]
